"use client";

import { useState } from "react";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function CopyReportButton({
  report,
  monitorName,
  monitorUrl,
}: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  report: any;
  monitorName: string;
  monitorUrl: string;
}) {
  const [copied, setCopied] = useState(false);

  function generateReportText() {
    return `INCIDENT REPORT — ${monitorName}
Generated by Pulse API Monitor

Endpoint: ${monitorUrl}
Started: ${new Date(report.started_at).toUTCString()}
Recovered: ${new Date(report.recovered_at).toUTCString()}
Duration: ${report.duration_minutes} minutes

SUMMARY
Failed checks: ${report.failed_checks}
Error codes: ${report.error_codes?.join(", ") || "None recorded"}
Peak response time: ${report.peak_response_time_ms ? report.peak_response_time_ms + "ms" : "N/A"}
Normal response time: ${report.avg_response_time_before_ms ? report.avg_response_time_before_ms + "ms" : "N/A"}

LIKELY CAUSE
${report.likely_cause}

---
Report generated by Pulse · pulse.app`;
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(generateReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <button
      onClick={handleCopy}
      className="flex items-center gap-1.5 text-[11px] text-neutral-500 dark:text-neutral-400 hover:text-[#080808] dark:hover:text-white border border-black/[0.08] dark:border-white/[0.08] hover:border-black/20 dark:hover:border-white/20 rounded-lg px-3 py-1.5 transition-all duration-200 flex-shrink-0"
      style={{ fontFamily: "'DM Mono', monospace" }}
    >
      {copied ? (
        <>
          <svg
            className="w-3 h-3 text-[#00cc6a] dark:text-[#00ff87]"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M5 13l4 4L19 7"
            />
          </svg>
          Copied
        </>
      ) : (
        <>
          <svg
            className="w-3 h-3"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
            />
          </svg>
          Copy report
        </>
      )}
    </button>
  );
}
