export interface IncidentReport {
  incidentId: string;
  monitorName: string;
  monitorUrl: string;
  startTime: string;
  endTime: string | null;
  durationMinutes: number | null;
  errorStatusCode: number | null;
  rootCause: string | null;
  confidence: number | null;
  baselineResponseMs: number | null;
  responseAtFailure: number | null;
  responseAtRecovery: number | null;
  failedChecks: number;
  estimatedRequestsAffected: number | null;
  anomalyDetectedBefore: boolean;
  generatedAt: string;
}

export function formatIncidentReport(report: IncidentReport): string {
  const lines: string[] = [];

  lines.push(`INCIDENT REPORT`);
  lines.push(`Generated by Pulse · ${new Date(report.generatedAt).toUTCString()}`);
  lines.push(``);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(``);
  lines.push(`MONITOR`);
  lines.push(`Name: ${report.monitorName}`);
  lines.push(`URL:  ${report.monitorUrl}`);
  lines.push(``);
  lines.push(`TIMELINE`);
  lines.push(`Start:    ${new Date(report.startTime).toUTCString()}`);
  lines.push(`End:      ${report.endTime ? new Date(report.endTime).toUTCString() : "Ongoing"}`);
  lines.push(`Duration: ${report.durationMinutes !== null ? report.durationMinutes + " minutes" : "Unknown"}`);
  if (report.anomalyDetectedBefore) {
    lines.push(`Note:     Performance degradation detected before outage`);
  }
  lines.push(``);
  lines.push(`WHAT HAPPENED`);
  lines.push(`Error:        ${report.errorStatusCode ? `HTTP ${report.errorStatusCode}` : "Connection timeout / No response"}`);
  if (report.rootCause) {
    lines.push(`Likely cause: ${report.rootCause}${report.confidence ? ` (${report.confidence}% confidence)` : ""}`);
  }
  lines.push(``);
  lines.push(`RESPONSE TIMES`);
  lines.push(`Baseline:    ${report.baselineResponseMs ? report.baselineResponseMs + "ms" : "N/A"}`);
  lines.push(`At failure:  ${report.responseAtFailure ? report.responseAtFailure + "ms" : "N/A"}`);
  lines.push(`At recovery: ${report.responseAtRecovery ? report.responseAtRecovery + "ms" : "N/A"}`);
  lines.push(``);
  lines.push(`IMPACT`);
  lines.push(`Failed checks: ${report.failedChecks}`);
  if (report.estimatedRequestsAffected !== null) {
    lines.push(`Est. impact:   ~${report.estimatedRequestsAffected.toLocaleString()} requests affected`);
  }
  lines.push(``);
  lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`Pulse API Monitor · pulse.app`);

  return lines.join("\n");
}
